### ISSUE TITLE
Optional TOR integration to support an onion-based PostgreSQL server?

### ISSUE THREAD

**Issue by ghost** [oldkingcone/slopShell#6]
Have you considered how viable/worthwhile it might be to support connections to a PostgreSQL server running on a TOR hidden service? The main benefit of this in my opinion aside from the anonymity perspective would be that it allows you to run the DBMS on a server without the need for port forwarding which can be a problem.

**Comment by oldkingcone** [comment]
I suggested ssh tunnels so that the postgres server itself isnt exposed to the world and all communication channels are encrypted heavily (think ssh keys over 8k bits if RSA or maxed at 16k bits), but most interactions will come over the diag_handler.php scripts so that can easily be hosted on a tor site so long as the host itself has the ability to communicate over tor. (writing something in Go if not, can cover that gap there are several libs that offer stand alone tor) If you have any suggestions I would love to hear them.

**Comment by oldkingcone** [comment]
added in check if the tor binary is supplied on the bots side, gives the option to download it. can add a bit more as far as naming conventions and more obfuscation in regards to the binary itself with server controlled names.
